import type { IconName } from "./content";

/* Icon per product-page challenge, assigned by meaning rather than keyword
   matching (a keyword pass put 45 of 157 on the same "chart" glyph).
   Keyed by the challenge string itself, so lib/products.ts stays untouched.
   Unmapped strings fall back at the call site. */
export const CHALLENGE_ICONS: Record<string, IconName> = {
  "Employees miss critical announcements buried in email or scattered across tools.": "broadcast",
  "Communication is one-way, with no room for employees to respond or be heard.": "chat",
  "Frontline and deskless employees remain disconnected from the organization.": "phone",
  "Managers lack visibility into whether messages are actually landing.": "compass",
  "There's no reliable measurement of communication effectiveness.": "chart",
  "Information is scattered across too many disconnected systems.": "plug",
  "Knowledge is lost instead of captured and shared.": "graduation",
  "Employee feedback is collected but rarely acted upon.": "checks",
  "Employee journeys are fragmented across disconnected systems and tools.": "plug",
  "Onboarding feels generic instead of personal to the role, team or location.": "graduation",
  "Employees don't know where to find people, policies or resources.": "compass",
  "Key life-cycle moments, promotions, anniversaries, transfers, go unnoticed.": "bell",
  "Managers have no visibility into how an employee's journey is actually going.": "users",
  "Experience quality varies wildly by geography, role and manager.": "globe",
  "HR teams spend more time administering processes than designing experiences.": "refresh",
  "There's no reliable way to measure whether employee experience is improving.": "chart",
  "Burnout is discovered only after an employee resigns or disengages.": "heart",
  "Wellbeing initiatives are generic, one-size-fits-all campaigns.": "broadcast",
  "Culture varies wildly across teams, managers and locations.": "globe",
  "Managers don't know which of their people are struggling.": "users",
  "Wellbeing surveys measure sentiment but rarely lead to real action.": "checks",
  "Support programs (EAP, mental health, benefits) go underused because employees don't know they exist.": "lifebuoy",
  "Leaders can't quantify the ROI of culture and wellbeing investment.": "chart",
  "Frontline and remote employees are the hardest to reach and support.": "phone",
  "Recognition happens inconsistently, often only top-down, rarely peer-to-peer.": "users",
  "Great work goes unnoticed because managers don't have time to track it.": "bell",
  "Recognition programs feel like a checkbox, not a genuine culture practice.": "heart",
  "Rewards catalogs are generic and don't reflect what employees actually value.": "palette",
  "No visibility into whether recognition is actually improving engagement or retention.": "compass",
  "Frontline and remote employees are recognized far less than office-based staff.": "phone",
  "HR can't tell which teams or managers under-recognize their people.": "chart",
  "Recognition and performance data live in separate systems, disconnected from insight.": "plug",
  "Workforce data lives in silos across HRIS, survey tools and spreadsheets.": "plug",
  "Leaders see lagging indicators, not real-time signals.": "pulse",
  "Analytics tools require a data team to interpret.": "chart",
  "No single source of truth for engagement, performance and attrition data together.": "compass",
  "Insights don't reach the managers who can actually act on them.": "users",
  "Reporting takes days or weeks to produce.": "refresh",
  "Sentiment is only measured once or twice a year via formal surveys.": "pulse",
  "Open-text feedback is too time-consuming to read and categorize manually.": "chat",
  "Warning signs of disengagement appear only after someone resigns.": "heart",
  "No way to track sentiment trends by team, manager or location over time.": "chart",
  "Leaders don't know if morale is improving or declining until it's too late.": "compass",
  "Leaders don't know if their engagement scores are actually good or bad.": "compass",
  "Internal-only metrics lack external context.": "globe",
  "Benchmark data is often outdated or too broad to be useful.": "refresh",
  "No visibility into how specific drivers (leadership, recognition, wellbeing) compare to peers.": "chart",
  "Board and executive reporting lacks credible external reference points.": "users",
  "Building executive reports manually takes days each cycle.": "refresh",
  "Reports are static snapshots, not connected to live data.": "pulse",
  "Executives get too much data and not enough clear recommendation.": "compass",
  "Different stakeholders (board, CHRO, business unit leads) need different views, but HR only has time to build one.": "users",
  "No consistent reporting cadence across the organization.": "chart",
  "Candidates go quiet or drop off between offer and start date.": "chat",
  "Onboarding is generic, not tailored to role or location.": "palette",
  "New hires don't know who to ask for help or where to find information.": "compass",
  "Early attrition is high because the first weeks feel disorganized.": "heart",
  "Managers don't have visibility into how onboarding is actually going.": "users",
  "Document collection and compliance tasks slow down day-one readiness.": "checks",
  "Organizations don't have an accurate, current picture of workforce skills.": "compass",
  "Skills data lives in outdated resumes or disconnected LMS systems.": "plug",
  "Leaders can't tell if they have the capability to execute strategic plans.": "chart",
  "Reskilling and upskilling investment is guesswork, not data-driven.": "graduation",
  "Employees don't have visibility into their own skill gaps or growth paths.": "rocket",
  "Critical skill gaps are discovered only when a project stalls.": "bell",
  "Leadership development programs aren't connected to actual team engagement data.": "plug",
  "Organizations can't tell which managers are effective versus which are struggling.": "users",
  "360 feedback happens once a year and quickly goes stale.": "refresh",
  "High-potential leaders aren't identified systematically.": "rocket",
  "Leadership gaps are only discovered after a team's engagement collapses.": "bell",
  "Coaching and development budgets aren't targeted to where they'd have the most impact.": "chart",
  "Workforce planning happens in spreadsheets, disconnected from real skills or engagement data.": "plug",
  "Headcount decisions are reactive, not tied to strategic forecasting.": "chart",
  "Leaders can't model the impact of attrition, growth, or reorganization scenarios.": "compass",
  "Skills gaps aren't factored into hiring and planning decisions.": "rocket",
  "Workforce plans go stale the moment they're finalized.": "refresh",
  "HR and Finance often plan headcount independently, with misaligned assumptions.": "users",
  "Access is switched off on the last day, and the relationship ends with it.": "lock",
  "Leavers chase HR for months afterwards for certificates and references.": "graduation",
  "Exit paperwork sits across email, drives and HR systems with no single home.": "plug",
  "Proven former employees are re-sourced through agencies at full cost.": "rocket",
  "Nobody knows where alumni went, or which ones would come back.": "compass",
  "Referrals from former employees are informal, untracked and unrewarded.": "users",
  "Employer brand is shaped by alumni stories the company never hears.": "palette",
  "There's no measure of what the alumni community is actually worth.": "chart",
  "Annual surveys are too infrequent to catch problems as they happen.": "pulse",
  "Survey fatigue reduces participation and honesty over time.": "heart",
  "Open-text feedback is time-consuming to analyze manually.": "chat",
  "Frontline and deskless employees are hard to reach via email-based surveys.": "phone",
  "Survey results rarely translate into consistent, tracked action.": "checks",
  "Leaders don't know which questions actually predict engagement or attrition.": "chart",
  "Annual surveys create long blind spots between measurement points.": "compass",
  "Issues surface only after they've already damaged morale or driven attrition.": "heart",
  "Different lifecycle stages (onboarding, exit, post-promotion) aren't listened to distinctly.": "bell",
  "Employees feel surveyed at, not listened to.": "chat",
  "Feedback arrives through scattered, disconnected channels.": "plug",
  "There's no continuous signal to tell leaders whether things are improving.": "pulse",
  "Open-text feedback is too voluminous to read and analyze manually.": "chat",
  "Important signals get buried under routine comments.": "bell",
  "Manual categorization is slow, inconsistent and subjective.": "refresh",
  "Leaders can't tell which themes are rising or fading over time.": "chart",
  "Multilingual feedback is especially hard to analyze consistently.": "globe",
  "The same issue gets described in many different ways.": "spark",
  "Surveys generate insight but rarely lead to consistent action.": "checks",
  "Managers don't know what to do with survey results.": "users",
  "Action items get assigned but never tracked to completion.": "check",
  "There's no accountability loop between feedback and follow-through.": "refresh",
  "Employees stop responding when they see nothing changes (\"survey fatigue born of inaction\").": "chat",
  "HR can't see which teams are actually acting on feedback.": "compass",
  "HR and IT teams are overwhelmed with repetitive routine queries.": "refresh",
  "Employees wait hours or days for answers to simple questions.": "chat",
  "Frontline and remote employees have no easy way to get help.": "phone",
  "Knowledge is scattered across policies, portals and people.": "graduation",
  "After-hours questions go unanswered.": "bell",
  "HR spends time on tickets instead of strategic work.": "lifebuoy",
  "Everyday tasks and approvals are scattered across email, chat and paper.": "checks",
  "Frontline employees have no structured way to receive and complete tasks.": "phone",
  "Managers can't see what's done and what's pending across their team.": "users",
  "Routine workflows (requests, approvals, checklists) are manual and slow.": "refresh",
  "Compliance tasks get missed without a system to enforce them.": "shield",
  "Work happens in silos disconnected from communication and learning.": "plug",
  "Frontline and deskless employees can't easily access traditional LMS platforms.": "phone",
  "Training content is long, dull and poorly completed.": "graduation",
  "Onboarding and compliance training are inconsistent across locations.": "globe",
  "Managers can't track training progress or readiness in real time.": "chart",
  "Content creation requires specialist tools and skills.": "palette",
  "Learning is disconnected from the rest of the employee experience.": "plug",
  "Workforce data is trapped in disconnected systems.": "plug",
  "Manual data syncing is slow, error-prone and stale.": "refresh",
  "New tools create yet another silo instead of connecting existing ones.": "compass",
  "IT worries about integration complexity and maintenance.": "shield",
  "Employee data has to be manually reconciled across platforms.": "users",
  "Point tools don't talk to each other, breaking workflows.": "checks",
  "Employee data is highly sensitive and a prime target.": "shield",
  "Global organizations face complex, varying data-privacy regulations.": "globe",
  "Security concerns block or delay HR technology adoption.": "rocket",
  "Role-based access must balance insight with confidentiality.": "lock",
  "Audit and compliance reporting is burdensome.": "chart",
  "AI features raise new questions about responsible data use.": "spark",
  "Enterprise software rollouts are slow, complex and risky.": "rocket",
  "Poor onboarding leads to low adoption and wasted investment.": "graduation",
  "Teams don't know how to get value after go-live.": "compass",
  "Configuration to unique org needs is daunting.": "palette",
  "Success depends on change management, not just software.": "users",
  "Vendors disappear after the sale.": "lifebuoy",
  "Leaders have data but struggle to turn it into decisions.": "compass",
  "Insights are scattered across dashboards no one has time to read.": "chart",
  "Getting an answer requires knowing which report to open.": "chat",
  "Non-analysts can't easily interrogate workforce data.": "users",
  "Decisions rely on gut feel because data is hard to access.": "lock",
  "The gap between “we have data” and “we know what to do” is wide.": "spark",
  "Employees and managers are overloaded and miss what matters.": "bell",
  "Important signals (a disengaged team member, an overdue task) go unnoticed.": "pulse",
  "Managers lack time to analyze data and decide what to act on.": "users",
  "Employees don't know what to prioritize day to day.": "checks",
  "Support and guidance aren't personalized or proactive.": "lifebuoy",
  "AI in most tools is reactive, it waits to be asked.": "spark",
};
