/* Design tokens, Light mode, straight from the Figma variable collections. */
export const T = {
  white: "#ffffff",
  canvas: "#fcfcfd",
  soft: "#f6f6f8",
  track: "#efeff3",
  line: "#ebebef",
  strong: "#c9c9d4",
  faint: "#9b9ea8",
  muted: "#6b6e78",
  ink: "#1a1b1f",
  brand: "#7c5cf8",
  brandStrong: "#6a5cf0",
  brandSoft: "#f1effd",
  teal: "#23d7be",
  blue: "#3b9eff",
  coral: "#ff8a5b",
  success: "#17a35e",
  successSoft: "#e6f7ee",
  danger: "#d44a50",
  dangerSoft: "#fdeceb",
  warning: "#e08c1f",
  warningSoft: "#fdf3e0",
  info: "#3b9eff",
  infoSoft: "#eaf2ff",
  butter: "#fbf7ef",
  butterInk: "#7a6437",
  butterRing: "#f3e8d3",
  signal: "#fb4b43",
};
